import ClientProviders from "@/components/ClientProviders";
import NavbarFooterWrapper from "@/components/NavbarFooterWrapper";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        // className={inter.className}
        className="flex flex-col justify-between min-h-[100vh]"
      >
        <ClientProviders>
          <NavbarFooterWrapper>{children}</NavbarFooterWrapper>
        </ClientProviders>
      </body>
      <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss={false}
        draggable
        pauseOnHover={false}
        theme="light"
      />
    </html>
  );
}
